# Generated by Django 5.0.4 on 2024-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduSensorAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
