# Generated by Django 5.0.4 on 2024-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduSensorAPI', '0002_sensordata_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
    ]
