# Generated by Django 5.0.4 on 2024-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduSensorAPI', '0003_alter_sensordata_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_humidity', models.FloatField(blank=True, null=True)),
                ('min_humidity', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
