# Generated by Django 5.0.4 on 2024-11-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduSensorAPI', '0004_alertthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertthreshold',
            name='last_alert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
