# Generated by Django 5.0.4 on 2025-01-23 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduSensorAPI', '0006_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
